.github/workflows/release-tag.yml

release时自动从changelog.md抽出当前版本的changelog 写入release description

chore: release action

---

.gitignore
components/form/interface.ts
package.json
scripts/build-types.js

难难难
https://github.com/import-js/eslint-plugin-import/issues/1868

fix: 解决 eslint-plugin-import 无法识别 exports imports 问题

---

components/scrollbar/bar.vue
components/scrollbar/scrollbar.vue
components/select/optionList.tsx
components/select/select.vue
components/virtual-list/virtualList.tsx
docs/.vitepress/components/scrollbar/index.md
docs/.vitepress/components/select/common.vue
docs/.vitepress/components/select/filterable.vue
docs/.vitepress/components/select/index.md
docs/.vitepress/components/virtualList/horizontal.vue

1. 优化虚拟滚动，当子项高度变化时更新scrollbar
2. select提供scroll事件
3. 优化scrollbar，mousedown事件阻止默认动作，避免导致select焦点变化

fix: 一些bug修复

---

components/cascader-panel/props.ts
components/cascader-panel/utils.ts
components/cascader/cascader.vue
components/select/props.ts
docs/.vitepress/components/cascader/basic.vue
docs/.vitepress/components/cascader/multiple.vue
docs/.vitepress/components/configProvider/changeLocale.vue

Component cascader perf

---

components/input-number/input-number.vue

fix: 修复 input-number 加减 disbled 判断逻辑

---

components/select-trigger/selectTrigger.vue
components/select-trigger/style/index.less

fix: 修复select当设置filterable和disable时样式问题

---

components/layout/aside.vue
components/layout/style/index.less
docs/.vitepress/components/layout/fixed.vue

fix: 修复window下layout组件收起时出现滚动条的问题

---

components/popper/popper.tsx
components/popper/usePopper.ts
components/style/core/motion/slide.less

refactor: 优化popper的动画,减少渲染次数

---

components/select/optionList.tsx
components/select/select.vue

feat: 当select组件达到限制个数时无法再点击选项

---

components/select/style/index.ts
components/tree/style/index.ts
components/virtual-list/listItem.ts
components/virtual-list/props.ts
components/virtual-list/virtualList.tsx
docs/.vitepress/components/virtualList/index.md

Refactor table

---

docs/.vitepress/components/tag/edit.vue
docs/.vitepress/components/tag/index.md
docs/.vitepress/components/tag/withForm.vue

Docs tag form

---

components/space/style/index.less
components/space/style/index.ts
components/space/style/mixin.less
components/style.ts

space组件增加空的style文件，fix import的时候style文件加载异常的问题。

fix: space组件import

---

components/select/optionList.tsx
components/select/props.ts
components/select/select.vue
docs/.vitepress/components/select/index.md
docs/.vitepress/components/select/options.vue

feat: select支持配置valueLabel

---

components/button/style/index.less

fix: 修复 small button radius 问题

---

components/modal/modal.tsx
components/modal/style/index.less
docs/.vitepress/components/modal/common.vue
docs/.vitepress/components/modal/index.md

feat: modal 新增垂直居中

---

components/menu/const.ts
components/menu/interface.ts
components/menu/menuItem.tsx
components/menu/subMenu.tsx
docs/.vitepress/components/menu/index.md
docs/.vitepress/components/menu/options.vue

fix: 组件menu的model支持类型Number

---

components/tabs/helper.ts
components/tabs/tab.tsx

fix: tabs closable

---

components/menu/menu.tsx
docs/.vitepress/components/menu/options.vue

menu支持在没有slots.default的情况下，传入异步options

fix: menu支持异步options

---

components/upload/upload.tsx

fix: 修复 upload 组件上文文件问题

---

components/input/style/index.less
components/scrollbar/const.ts
components/scrollbar/scrollbar.vue
components/scrollbar/style/index.less
components/scrollbar/style/mixin.less
components/scrollbar/useScrollbar.ts
components/table/components/bodyTable.tsx
components/table/components/virtualTable.tsx
components/table/style/index.less
components/table/useTableColumn.ts
components/table/useTableStyle.ts
components/virtual-list/props.ts
components/virtual-list/virtualList.tsx
docs/.vitepress/components/scrollbar/index.md
docs/.vitepress/components/scrollbar/scrollbar.vue
docs/.vitepress/components/virtualList/index.md

feat: table不只在fixed时滚动阴影

---

components/select/select.vue

fix: 修复select下拉选项宽度问题

---

components/table/components/cell.tsx
components/table/components/expandTr.tsx
components/table/components/label.tsx
docs/.vitepress/components/table/index.md

fix: 修复table渲染问题

---

components/scrollbar/style/index.less

refactor: 放弃 scrollbar 只能在区域内滚动

---

components/select-tree/selectTree.vue
components/select-trigger/interface.ts
components/select-trigger/renderTag.tsx
components/select-trigger/selectTrigger.vue
components/select/props.ts
components/select/select.vue
components/select/style/index.less
docs/.vitepress/components/select/action.vue
docs/.vitepress/components/select/addon.vue
docs/.vitepress/components/select/filterable.vue
docs/.vitepress/components/select/index.md
docs/.vitepress/components/select/tag.vue
docs/.vitepress/components/selectTree/index.md
docs/.vitepress/components/selectTree/labelField.vue

feat: Select组件添加renderTag实现自由定制tag内容, 添加操作插槽

---

components/tooltip/tooltip.tsx
docs/.vitepress/components/tooltip/confirm.vue

fix: tooltip confirm

---

components/ellipsis/ellipsis.tsx
components/menu/menuGroup.tsx
components/menu/menuItem.tsx
components/menu/subMenu.tsx
components/scrollbar/scrollbar.vue
components/select/optionList.tsx
components/table/column.vue
components/table/table.tsx
components/table/useTableStyle.ts
components/time-picker/time-picker.vue
docs/.vitepress/components/table/index.md

refactor: 优化一些class和style参数

---

components/date-picker/useCalendar.ts
components/input/input.vue
docs/.vitepress/config.js

fix: datePicker 3月切 2 月选择问题

---

docs/.vitepress/components/icon/index.md

docs: 优化 icons 文档

---

components/ellipsis/ellipsis.tsx
docs/.vitepress/components/ellipsis/common.vue
docs/.vitepress/components/ellipsis/index.md
docs/.vitepress/components/ellipsis/line.vue
docs/.vitepress/components/ellipsis/tooltip.vue

feat: ellipsis新增定制Tooltip功能

---

components/_util/components/fadeInExpandTransition.tsx
components/menu/subMenu.tsx
components/style/core/motion.less
components/style/core/motion/fade-in-height-expand.less
components/style/core/motion/fade-in-width-expand.less

refactor: 优化menu展开动画

---

components/table/components/expandTr.tsx
components/table/style/index.less
components/table/table.tsx
components/table/useTableExpand.ts
docs/.vitepress/components/table/expand.vue
docs/.vitepress/components/table/index.md
pnpm-lock.yaml

https://github.com/WeBankFinTech/fes-design/issues/94

feat: 手动展开行

---

docs/.vitepress/components/table/index.md

doc(table): event argument

---

components/pagination/jumper.tsx
components/pagination/pagination.tsx
components/pagination/sizes.tsx
components/pagination/style/index.less
components/pagination/style/index.ts
docs/.vitepress/components/pagination/combination.vue
docs/.vitepress/components/pagination/index.md
pnpm-lock.yaml

Pagination

---

components/popper/popper.tsx
components/popper/props.ts

feat: popper的popperClass支持obect和array

---

components/date-picker/datePicker.vue
components/date-picker/style/index.less
components/input/inputInner.vue

fix: 修复date-picker圆角问题 + 修复 input tab 选中问题

---

components/form/style/index.less

fix: 表单 inline 不换行问题

---

components/pagination/style/index.less

fix: 快速跳转样式被覆盖问题

---

components/tree/props.ts
components/tree/tree.tsx
docs/.vitepress/components/tree/common.vue
docs/.vitepress/components/tree/index.md

feat: Tree增加cancelable配置是否可以取消选中

---

package.json
pnpm-lock.yaml

docs: 解决 playground 问题

---

components/tag/style/index.less
docs/.vitepress/components/tag/basic.vue
docs/.vitepress/components/tag/closable.vue
docs/.vitepress/components/tag/edit.vue
docs/.vitepress/components/tag/index.md
docs/.vitepress/components/tag/size.vue
docs/.vitepress/components/tag/theme.vue
docs/.vitepress/components/tag/tooltip.vue
docs/.vitepress/components/tag/withIcon.vue

style: tag组件样式优化

---

components/table/useTable.ts
components/table/useTableLayout.ts
components/table/useTableStyle.ts

fix: 修复设置height但是因为数据延迟获得而不滚动问题

---

components/input-number/input-number.vue
components/input-number/style/index.ts
components/modal/index.ts
docs/.vitepress/components/inputNumber/common.vue
docs/.vitepress/theme/IconDoc/IconDoc.jsx

fix: input 无法输入小数 + icon docs 复制 + Modal ts 问题

---

components/form/style/index.less
docs/.vitepress/components/form/inline.vue

fix: 修复inline-form样式问题

---

components/_theme/base.ts
components/image/image.vue
components/image/preview-group.tsx
components/image/preview.vue
components/image/props.ts
components/image/style/index.less
components/table/const.ts
components/table/style/index.less
components/table/table.tsx
docs/.vitepress/components/image/index.md
docs/.vitepress/components/image/multiPreview.vue
docs/.vitepress/components/image/preview.vue
docs/.vitepress/components/table/index.md

Feat image

---

components/upload/fileList.vue
components/upload/upload.tsx
docs/.vitepress/components/upload/index.md
docs/.vitepress/components/upload/previewUpload.vue

feat: upload 添加 file slot

---

components/checkbox-group/style/index.less
components/radio-group/style/index.less
docs/.vitepress/components/checkbox/group.vue
docs/.vitepress/components/radio/group.vue

fix: CheckboxGroup和RadioGroup默认可换行

---

components/_util/use/useResize.ts
components/table/table.tsx
components/table/useTableLayout.ts

feat:  Table组件在没计算出宽度前不渲染,避免导致撑开页面 & 优化keepalive下resize的逻辑

---

components/_util/download.ts
components/image/image.vue
components/image/preview-group.tsx
components/image/preview.vue
components/image/props.ts
docs/.vitepress/components/image/index.md
docs/.vitepress/components/image/multiPreview.vue
docs/.vitepress/components/image/preview.vue

feat: Image支持配置下载

---

components/_util/utils.ts
components/popper/popper.tsx
components/popper/useScroll.ts

fix: 修复Select等组件的弹出层不跟随滚动

---

components/upload/style/index.less

fix: upload的close按钮居中

---

components/popper/popper.tsx

fix: 当popper弹窗大小改变时,需要更新位置

---

components/tabs/tabs.tsx
docs/.vitepress/components/tabs/closable.vue
docs/.vitepress/components/tabs/index.md

feat: tabs 添加 change 事件

---

components/input/input.vue
components/input/style/index.less
docs/.vitepress/components/input/common.vue
docs/.vitepress/vueTheme/core/styles/vt-flyout.css

feat: input[text] 支持 showWordLimit

---

components/form/style/index.less
docs/.vitepress/components/form/inline.vue

fix: Form组件的inline模式下row-gap在78存在兼容性问题,改为grid实现

---

components/draggable/useDraggable.ts

fix: dragable 动态插入值，不能拖拽问题

---

components/input-number/input-number.vue
components/input-number/style/index.less
components/input/input.vue
components/input/inputInner.vue
components/input/style/index.less
components/input/style/inputInner.less
components/time-picker/time-picker.vue

fix: input-number 修复 form 校验不通过时，边框变红问题

---

components/table/useTableColumn.ts

fix: Table组件修复因为fixed导致表头和列不一致的问题

---

components/select-trigger/selectTrigger.vue
components/select/select.vue

fix: Select当只有option只有value时,不把label设置为value,如果需要用户自行处理

---

components/scrollbar/bar.vue
components/scrollbar/const.ts
components/scrollbar/scrollbar.vue
components/scrollbar/style/index.less
components/select-tree/selectTree.vue
components/select-tree/style/index.less
components/table/components/bodyTable.tsx
components/virtual-list/props.ts
components/virtual-list/virtualList.tsx
docs/.vitepress/components/virtualList/index.md

-   [x] Bugfix
-   [ ] Docs
-   [x] Yes
-   [ ] No

fix: scrollbar能监听内容大小更新 &  scrollbar不内置z-index & 去掉virtual-list的rootTag属性

---

components/cascader/useData.ts
docs/.vitepress/components/selectCascader/async.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
fix：异步加载初始化渲染

fix: cascader组件初始化加载节点

---

components/drawer/style/index.less
components/modal/style/index.less

fix: FDrawer | FModal 关闭 icon 颜色加深

---

components/cascader/useData.ts
docs/.vitepress/components/selectCascader/async.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
cascader组件异步加载初始化渲染，兼容异步赋值的场景

Fix component cascader load

---

components/date-picker/helper.ts

fix: datePicker confirm 日期错误

---

components/date-picker/rangeInput.vue
components/date-picker/useRange.ts

fix: datePicker 聚焦问题 + range disabled 问题

---

components/time-picker/time-picker.vue

fix: time-picker 选 此刻 无法生效问题

---

components/draggable/useDraggable.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
f-darggable 通过modelvalue变长 加进来的不能拖拽。

fix(draggable): wait for dom updated when props changed

---

components/ellipsis/ellipsis.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: Ellipsis未渲染完毕时计算出是不tooltip,而实际上是需要tooltip

---

components/cascader/cascaderNode.tsx
components/cascader/useData.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
异步加载父节点时，兼容没有子节点返回的场景。

fix: 异步加载兼容无子节点的场景

---

components/image/preview.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: Image预览图片大小不会超过可视区域

---

components/_theme/useTheme.ts
components/cascader/cascaderMenu.tsx
components/cascader/useCascaderMenu.ts
components/cascader/useCascaderNode.ts
components/date-picker/calendar.vue
components/date-picker/datePicker.vue
components/date-picker/useCalendar.ts
components/date-picker/useRange.ts
components/image/preview-group.tsx
components/layout/layout.vue
components/select-cascader/helper.ts
components/select-trigger/renderTag.tsx
components/space/space.tsx
components/tag/interface.ts
components/tag/props.ts
components/tag/tag.vue
components/tag/useHover.ts

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

Refactor tag setup to define component

---

components/select/option.vue
components/select/optionList.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix:  Select修复slot 不在render中执行的问题

---

components/draggable/directive.ts

fix: dragable 指令引发 vue 组件渲染异常

---

components/tabs/tabs.tsx
docs/.vitepress/components/tabs/common.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: tabPane为空时正常显示

---

components/date-picker/calendar.vue
docs/.vitepress/components/datePicker/common.vue

fix: date-picker 时间初始化问题

---

components/date-picker/const.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
change type of `type` to make datepicker easier to use.

fix(datepicker): type

---

components/scrollbar/const.ts
components/scrollbar/scrollbar.vue
components/table/components/bodyTable.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 修复table滚动时shadow 样式被固定列覆盖问题

---

components/tree/const.ts
components/tree/interface.ts
components/tree/props.ts
components/tree/style/index.less
components/tree/tree.tsx
components/tree/treeNode.tsx
components/tree/useDrag.ts
docs/.vitepress/components/tree/default.vue
docs/.vitepress/components/tree/drag.vue
docs/.vitepress/components/tree/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: Tree支持拖拽

---

components/ellipsis/ellipsis.tsx
docs/.vitepress/components/ellipsis/common.vue
docs/.vitepress/components/ellipsis/index.md

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: Ellipsis添加content属性，能文本变化从而更新省略

---

components/cascader/const.ts
components/cascader/props.ts
components/date-picker/calendar.vue
components/date-picker/const.ts
components/date-picker/helper.ts
components/date-picker/pickerHandler.ts
components/date-picker/useCalendar.ts
components/date-picker/useRange.ts
components/form/const.ts
components/form/form.vue
components/form/formItem.vue
components/pagination/sizes.tsx
components/select/index.ts
components/select/interface.ts
components/select/option.tsx
components/steps/const.ts
components/steps/step.tsx
components/steps/steps.tsx
components/tree/const.ts
components/tree/props.ts

fix: 将 enum 属性改成字符串，避免使用组件时类型提示异常

---

components/table/column.vue
components/table/components/colgroup.tsx
components/table/components/virtualTable.tsx
components/table/table.tsx
components/table/useTableLayout.ts

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

refactor: 优化Table渲染

---

components/index.ts
components/locales/lang/enUS.ts
components/locales/lang/zhCN.ts
components/upload/index.ts
components/upload/style/index.less
components/upload/style/index.ts
components/upload/upload.tsx
components/upload/uploadDragger.tsx
components/upload/useUpload.ts
components/upload/utils.ts
docs/.vitepress/components/upload/drag.vue
docs/.vitepress/components/upload/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: upload支持拖拽上传

---

components/select-tree/selectTree.vue
components/tree/tree.tsx
components/tree/useData.ts
components/tree/useFilter.ts
components/tree/useState.ts
docs/.vitepress/components/selectTree/filterable.vue
docs/.vitepress/components/selectTree/index.md
docs/.vitepress/components/tree/virtualList.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
https://github.com/WeBankFinTech/fes-design/issues/154

fix: 修复超出1W数据时过滤Tree卡顿问题

---

components/table/useTableSelect.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: Table全选在数据改变后不更新

---

components/table/column.vue
components/table/helper.ts
components/table/useTableColumn.ts
docs/.vitepress/components/table/common.vue
docs/.vitepress/components/table/header.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 修复多级表头无法正确显示问题

---

components/pagination/style/index.less

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: Pagaintion组件按钮加入默认padding

---

components/table/style/index.less

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

Refactor: Table组件边框样式调整

---

components/upload/ajax.ts
components/upload/interface.ts
components/upload/upload.tsx
components/upload/useUpload.ts
docs/.vitepress/components/upload/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: Upload添加tansformResponse处理请求和timeout配置

---

components/form/const.ts
components/form/form.vue
components/form/style/index.less
docs/.vitepress/components/form/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [ ] No

fix: inline-form grid 布局自适应换行

---

docs/.vitepress/components/form/align.vue
docs/.vitepress/components/tabs/extend.vue
docs/.vitepress/components/tabs/withScroll.vue

docs: 修复文档样式问题

---

components/input-number/input-number.vue

fix: input-number 小数点后面不能输入0

---

components/form/style/index.less

fix: form label font-size 异常

---

components/select-trigger/style/index.less

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 修复Select等组件多选时gap样式兼容性差问题

---

components/draggable/draggable.vue
components/draggable/interface.ts
docs/.vitepress/components/draggable/index.md

feat: draggable slot 暴露 index

---

components/date-picker/useCalendar.ts
components/draggable/useDraggable.ts
docs/.vitepress/components/datePicker/rangeSelect.vue
docs/.vitepress/components/draggable/index.md
docs/.vitepress/components/draggable/vertical.vue

Fix aringlai

---

components/table/components/bodyTable.tsx
components/table/table.tsx
docs/.vitepress/components/table/common.vue
docs/.vitepress/components/table/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: Table在某些场景下支持列按照内容分配宽度

---

components/date-picker/calendar.vue
components/date-picker/calendars.vue
components/date-picker/datePicker.vue
components/date-picker/helper.ts
components/date-picker/rangeInput.vue
components/date-picker/use.ts
components/date-picker/useRange.ts

fix: datePicker 手动输入 disable 限制问题

---

components/steps/step.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#202 

fix: 修复垂直步骤条样式问题

---

components/table/components/header.tsx
components/table/components/label.tsx
components/table/components/td.tsx
components/table/style/index.less
components/table/useTableLayout.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 修复table样式问题

---

components/select/optionList.tsx
components/select/props.ts
components/select/select.vue
docs/.vitepress/components/select/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: select支持配置弹窗样式

---

components/_util/use/useResize.ts
components/scrollbar/scrollbar.vue
components/table/useTableStyle.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: scrollbar监听最外层容器大小变化而重新计算滚动条

---

components/table/useTableSelect.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: clearSelection清除全部选中数据

---

components/tree/tree.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 修复Tree组件checkedKeys默认值无效问题

---

components/radio-group/radio-group.vue
components/radio-group/useRadioGroup.ts
docs/.vitepress/components/radio/group.vue
docs/.vitepress/components/radio/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: RadioGroup可配置是否取消选项

---

components/cascader/cascaderNode.tsx
components/ellipsis/ellipsis.tsx
components/ellipsis/style/index.less
components/popper/popper.tsx
components/popper/props.ts
components/popper/usePopper.ts
components/popper/useTrigger.ts
components/select-trigger/selectTrigger.vue
components/select/optionList.tsx
components/table/components/cell.tsx
docs/.vitepress/components/select/common.vue

fix: 修复Select组件切换选项时选项超长文本省略不生效问题

---

components/select-tree/selectTree.vue
docs/.vitepress/components/selectTree/common.vue

fix: 修复selectTree默认值不显示问题

---

components/_util/vnode.ts

fix: flatten节点会配置Fragment包裹节点的key,避免出现渲染异常

---

components/select-trigger/selectTrigger.vue

fix: 修复select多选时过滤文本展示不全的问题

---

components/draggable/directive.ts
components/draggable/draggable.tsx
components/draggable/useDraggable.ts
docs/.vitepress/components/draggable/checkDragEnd.vue
docs/.vitepress/components/draggable/container.vue
docs/.vitepress/components/draggable/horizontal.vue
docs/.vitepress/components/draggable/index.md
docs/.vitepress/components/draggable/instruction.vue
docs/.vitepress/components/draggable/instructionCheckDragEnd.vue
docs/.vitepress/components/draggable/vertical.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

Refactor drag

---

components/table/components/bodyTable.tsx
components/table/interface.ts
components/table/table.tsx
components/table/useTable.ts
components/table/useTableDrag.ts
docs/.vitepress/components/table/draggable.vue
docs/.vitepress/components/table/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: table支持拖拽

---

docs/.vitepress/components/pagination/base.vue
docs/.vitepress/components/pagination/combination.vue
docs/.vitepress/components/pagination/index.md
docs/.vitepress/components/pagination/sizes.vue
docs/.vitepress/components/pagination/total.vue

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

docs: 补充 Pagination 组件文档

---

components/date-picker/calendar.vue
components/date-picker/helper.ts
components/date-picker/useCalendar.ts

fix: Date-picker 默认时间范围00:00:00-23:59:59

---

components/_util/use/useModel.ts
components/cascader/useData.ts
components/cascader/useState.ts
components/date-picker/calendars.vue
components/select-trigger/selectTrigger.vue
components/select-trigger/style/index.less
components/select/props.ts
components/select/select.vue
components/table/column.tsx
components/table/useTableExpand.ts
components/table/useTableSelect.ts
components/tree/useCheck.ts
components/tree/useCurrentData.ts
components/tree/useState.ts
docs/.vitepress/components/select/multiple.vue
docs/.vitepress/components/table/checkbox.vue
docs/.vitepress/components/tree/virtualList.vue

-   [x] Bugfix
-   [ ] Yes
-   [x] No

fix: 修复useNormalModel可能丢失响应性问题

---

components/table/interface.ts

fix: table actionType 类型问题

---

components/draggable/directive.ts
components/table/table.tsx
docs/.vitepress/components/table/draggable.vue
docs/.vitepress/components/table/index.md

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: draggable指令兼容只有updated场景

---

components/_util/use/useModel.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 修复Select组件v-model未初始化+多选导致内部状态不同步更新到组件外问题

---

components/draggable/directive.ts
components/draggable/draggable.tsx
components/draggable/useDraggable.ts
components/tooltip/tooltip.tsx
docs/.vitepress/components/draggable/index.md

Fix draggable

---

components/_theme/useTheme.ts
components/_util/utils.ts
components/config-provider/configProvider.tsx
components/config-provider/const.ts
docs/.vitepress/components/configProvider/changeLocale.vue
docs/.vitepress/theme/components/exampleRepl.vue

fix: config provide getContainer 没给默认值异常

---

components/cascader/useData.ts
docs/.vitepress/components/selectCascader/async.vue
docs/.vitepress/components/selectCascader/custom.vue
docs/.vitepress/components/selectCascader/index.md

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: Cascader组件自定义选项字段配置不生效

---

components/date-picker/style/index.less

fix: datePicker range 样式问题

---

components/draggable/directive.ts
components/table/components/bodyTable.tsx
docs/.vitepress/components/table/draggable.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 修复Table组件开关draggable不起作用

---

components/table/useTableSelect.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 修复Table无数据时会全选问题

---

components/tabs/tab.tsx
components/tabs/tabs.tsx

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [ ] No

fix: tabs默认选中优化

---

components/tree/helper.ts
components/tree/tree.tsx
components/tree/useCurrentData.ts
components/tree/useExpand.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
close #237 

fix: 修复Tree组件手风琴模式问题

---

components/table/useTableSort.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 修复Table组件未设置排序能排序问题

---

components/form/formItem.vue
components/form/interface.ts
docs/.vitepress/components/form/complexValidate.vue
docs/.vitepress/components/form/index.md
pnpm-lock.yaml

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [ ] No

feat: 1.formItem支持value 2.formItem span 取整

---

components/table/components/bodyTable.tsx
components/table/components/noData.tsx
components/table/components/tr.tsx
components/table/interface.ts
components/table/table.tsx
components/table/useTable.ts

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: Table组件支持empty插槽

---

components/date-picker/const.ts
components/descriptions/descriptions.tsx
components/draggable/directive.ts
components/draggable/draggable.tsx
components/form/interface.ts
components/table/table.tsx
package.json
pnpm-lock.yaml

fix: 循环依赖问题

---

components/button/style/index.less

refactor: 优化 btn small 样式

---

components/image/preview.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: image组件新增预览拖拽查看

---

package.json
pnpm-lock.yaml
scripts/build-umd.js

fix: 修复 umd 编译问题

---

components/table/components/virtualTable.tsx
components/virtual-list/listItem.ts
components/virtual-list/props.ts
components/virtual-list/virtual.ts
components/virtual-list/virtualList.tsx
docs/.vitepress/components/virtualList/horizontal.vue
docs/.vitepress/components/virtualList/index.md
docs/.vitepress/components/virtualList/vertical.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
https://github.com/WeBankFinTech/fes-design/issues/224

feat: VirtualList支持配置height和maxHeight

---

components/_util/interface.ts
components/checkbox-group/checkbox-group.vue
components/checkbox/checkbox.vue
components/radio-group/radio-group.vue
components/radio-group/useRadioGroup.ts
components/radio/radio.vue
components/select/select.vue
docs/.vitepress/components/checkbox/index.md
docs/.vitepress/components/checkbox/options.vue
docs/.vitepress/components/radio/index.md
docs/.vitepress/components/radio/options.vue
pnpm-lock.yaml

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: checkbox&radio新增options支持

---

components/cascader/cascaderMenu.tsx
components/cascader/cascaderNode.tsx
components/cascader/props.ts
components/collapse/collapseExpose.ts
components/collapse/collapseItemExpose.ts
components/date-picker/calendars.vue
components/date-picker/datePicker.vue
components/date-picker/pickerHandler.ts
components/date-picker/useCalendar.ts
components/ellipsis/ellipsis.tsx
components/form/form.vue
components/form/interface.ts
components/grid/__tests__/grid.jsx
components/input/inputInner.vue
components/input/props.ts
components/tooltip/style/index.less
components/upload/const.ts
components/upload/trigger.vue
components/upload/uploadDragger.tsx
components/upload/useUpload.ts
docs/.vitepress/components/datePicker/common.vue
docs/.vitepress/components/datePicker/disabled.vue
docs/.vitepress/components/datePicker/index.md
docs/.vitepress/components/datePicker/multiple.vue

fix: 日期选择支持多选

---

components/space/space.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: Space空插槽问题

---

components/popper/popper.tsx
components/popper/useTrigger.ts
docs/.vitepress/components/dropdown/trigger.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: Popper组件可切换trigger

---

components/_style.ts
components/index.ts
components/radio-button/index.ts
components/radio-button/radio-button.tsx
components/radio-button/style/index.less
components/radio-button/style/index.ts
components/radio-group/interface.ts
components/radio-group/radio-group.vue
components/radio-group/style/index.less
docs/.vitepress/components/dropdown/index.md
docs/.vitepress/components/radio/button.vue
docs/.vitepress/components/radio/index.md
docs/.vitepress/components/radio/options.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: RadioGroup支持按钮组

---

components/menu/const.ts
components/menu/menu.tsx
components/menu/menuGroup.tsx
components/menu/menuItem.tsx
components/menu/subMenu.tsx
components/menu/useChildren.ts
components/menu/useMenu.ts
components/menu/useParent.ts
components/steps/interface.ts
components/steps/step.tsx
docs/.vitepress/components/steps/common.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

refactor: 重构Steps和Menu组件，去掉父子组件之间的强依赖

---

components/date-picker/datePicker.vue
components/date-picker/rangeInput.vue
components/date-picker/style/index.less

fix: datePicker 修复表单样式校验问题

---

components/select-trigger/style/index.less

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 修复Select disabled 时的样式问题

---

components/steps/interface.ts
components/steps/step.tsx
components/steps/steps.tsx
docs/.vitepress/components/steps/common.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 修复Steps组件未处理子组件删减逻辑

---

components/skeleton/skeleton.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: skeleton源码类型检查OK

---

components/checkbox-group/useCheckboxGroup.ts
components/form/index.ts
components/index.ts
components/input/style/index.less
components/input/style/inputInner.less
components/popper/popper.tsx
components/popper/props.ts
components/popper/usePopper.ts
components/select-trigger/style/index.less
components/select/interface.ts
components/select/optionList.tsx
components/select/props.ts
components/select/select.vue
components/select/style/index.less
docs/.vitepress/components/select/common.vue
docs/.vitepress/components/select/customTag.vue
docs/.vitepress/components/select/index.md
docs/.vitepress/components/select/optionDisabled.vue
docs/.vitepress/components/select/tag.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: 优化输入框光标颜色 & Select组件支持输入新选项 & Select组件支持按下enter选择

---

components/virtual-list/virtualList.tsx
docs/.vitepress/components/virtualList/index.md

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 修复虚拟滚动组件scrollToBottom问题

---

components/image/image.vue
components/image/preview.vue
components/modal/modalApi.tsx
docs/.vitepress/components/image/index.md
docs/.vitepress/components/image/preview.vue
docs/.vitepress/components/modal/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [ ] No

Image预览挂载&Modal全局配置

---

components/locales/lang/enUS.ts
components/locales/lang/zhCN.ts
components/select/optionList.tsx
components/select/style/index.less

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: Select组件中自定义选项添加标记

---

components/scrollbar/bar.vue
components/table/style/index.less

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 避免Table组件当bodyWrapper叠加scrollbar时高度为100%可能计算出错误高度

---

components/select/optionList.tsx
components/select/select.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: Select组件支持empty插槽

---

components/menu/menu.tsx
components/menu/subMenu.tsx
components/menu/useParent.ts
docs/.vitepress/components/menu/index.md

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: Menu组件的expandKeys支持双向绑定

---

components/_util/use/useEsc.ts
components/date-picker/datePicker.vue
components/input-number/input-number.vue
components/input/input.vue
components/input/inputInner.vue
components/modal/modal.tsx
components/select-cascader/selectCascader.vue
components/select-tree/selectTree.vue
components/select/select.vue
components/switch/switch.vue
components/time-picker/time-picker.vue

-   [x] Bugfix
-   [x] No
修复 input-number 聚焦问题
修复 innerDisabled 拼写错误问题
modal 添加 esc 能力

feat: modal 添加 esc 快捷键

---

components/modal/style/index.less

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [ ] No

refactor: modal全屏滚动条问题

---

components/date-picker/helper.ts

fix: 修复 maxRange 问题

---

components/input/inputInner.vue

fix: 修复date-picker 和 time-picker 弹窗问题

---

components/table/components/headerTable.tsx
components/table/table.tsx
docs/.vitepress/components/table/index.md

避免子组件渲染,减少执行脚本
-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

refactor: 优化table性能

---

components/ellipsis/ellipsis.tsx
components/form/interface.ts
components/input/input.vue
components/input/props.ts
scripts/build-types.js

fix: 修复类型异常

---

components/tooltip/tooltip.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(tooltip): 修复处理popperClass不正确问题

---

components/form/form.vue
components/form/interface.ts
docs/.vitepress/components/form/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: form支持inlineItemGap属性

---

components/_util/getElementFromRef.ts
components/_util/utils.ts
components/popper/popper.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 修复 popper trigger 纯文本节点导致异常

---

docs/.vitepress/components/upload/customerUpload.vue
docs/.vitepress/components/upload/index.md

docs: 优化 upload 文档

---

components/scrollbar/scrollbar.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(scrollbar): 修复scrollbar组件在水平滚动时,无法监听内容大小变化问题

---

components/_theme/useTheme.ts
components/radio-group/radio-group.vue
components/radio-group/style/index.ts

fix: radio-group options 丢失 radio 样式问题

---

components/radio-group/const.ts
components/radio-group/interface.ts
components/radio-group/radio-group.vue
components/radio-group/style/index.less
components/radio-group/useRadioGroup.ts
package.json
pnpm-lock.yaml

fix: radio-group 类型异常

---

components/table/column.tsx
components/table/helper.ts
components/table/table.tsx
components/table/useTable.ts
components/table/useTableColumn.ts
components/tabs/helper.ts
components/tabs/tab-pane.vue
components/tabs/tabs.tsx
docs/.vitepress/components/table/bordered.vue
docs/.vitepress/components/table/columns.vue
docs/.vitepress/components/table/index.md
docs/.vitepress/components/tabs/index.md
docs/.vitepress/components/tabs/panes.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: Table和Tabs支持列配置属性

---

components/input/inputInner.vue
docs/.vitepress/components/input/event.vue
docs/.vitepress/components/input/index.md

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 修复输入框输入后回车两次触发change事件

---

components/_util/components/lazyTeleport.ts
components/_util/getElementFromRef.ts
components/_util/getElementFromVueInstance.ts
components/_util/noticeManager.tsx
components/_util/use/useClickOutSide.ts
components/_util/use/useLockScreen.ts
components/_util/use/useResize.ts
components/_util/use/useScrollX.ts
components/_util/use/useSelect.ts
components/_util/utils.ts
components/carousel/arrow.tsx
components/carousel/carousel.tsx
components/carousel/useCarousel.ts
components/carousel/useCarouselItem.ts
components/cascader/cascader.tsx
components/cascader/cascaderMenu.tsx
components/cascader/helper.ts
components/cascader/useCascaderMenu.ts
components/cascader/useCascaderNode.ts
components/cascader/useData.ts
components/cascader/useState.ts
components/collapse/collapse.vue
components/config-provider/useLocale.ts
components/dropdown/dropdown.tsx
components/form/form.vue
components/image/preview.vue
components/popper/popper.tsx
components/popper/usePopper.ts
components/virtual-list/listItem.ts

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

refactor: 根据chatgpt提的意见优化utils模块

---

components/dropdown/dropdown.tsx

fix: 修复 dropdown 类型问题

---

components/grid/gridItem.vue
components/grid/style/index.less
components/grid/style/mixin.less
docs/.vitepress/components/grid/index.md
docs/.vitepress/components/grid/responsive.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: grid组件支持响应式布局

---

components/collapse/collapse.vue
components/collapse/collapseExpose.ts
components/collapse/collapseItem.vue
components/collapse/common.ts
components/collapse/style/index.less
components/collapse/useCollapseItem.ts
docs/.vitepress/components/collapse/accordion.vue
docs/.vitepress/components/collapse/embedded.vue
docs/.vitepress/components/collapse/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [ ] No

refactor: Collapse样式优化

---

components/table/column.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(table): 修复Table组件ColumnChildren类型问题

---

docs/.vitepress/components/descriptions/index.md

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

doc: 修正FDescriptions组件doc描述问题

---

components/radio-group/const.ts
components/radio-group/useRadioGroup.ts
components/select/props.ts
docs/.vitepress/components/radio/index.md

-   [x] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

fix: 更正RadioGroup文档 & 修复RadioGroup默认值为false问题

---

components/icon/IconWrapper.tsx
docs/.vitepress/components/icon/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: Icon支持size和color配置

---

components/radio-button/style/index.less

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: radiobtn 颜色设置为白色

---

components/date-picker/useCalendar.ts

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [ ] No

fix: 日期月份切换大小月问题

---

components/_theme/applyTheme.ts
components/_theme/base.ts
components/_theme/interface.ts
components/carousel/arrow.tsx
components/carousel/carousel-item.tsx
components/carousel/interface.ts
components/checkbox-group/checkbox-group.vue
components/checkbox-group/const.ts
components/checkbox-group/useCheckboxGroup.ts
components/config-provider/const.ts
components/icon/IconWrapper.tsx

refactor: 优化 ts type

---

components/_theme/base.ts
components/date-picker/style/index.less

fix: 修复主题问题

---

components/date-picker/style/index.less

fix: 日期选择箭头颜色

---

docs/.vitepress/theme/components/exampleRepl.vue

docs: 优化 playgound

---

components/dropdown/dropdown.tsx
components/dropdown/style/index.less
components/popper/popper.tsx
components/popper/usePopper.ts
components/style/core/motion/slide.less
components/style/mixins/motion.less
docs/.vitepress/components/dropdown/check.vue
docs/.vitepress/components/dropdown/index.md
package.json
pnpm-lock.yaml

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: Dropdown支持配置显示选择选项

---

components/input/style/inputInner.less

fix: 隐藏 edge 浏览器 password 的眼睛

---

components/modal/modalApi.tsx

-   [√] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [√] No

fix: 修复二次包装fes-design生成声明文件时出现私有名的错误

---

components/_theme/base.ts
components/_theme/interface.ts

feat: theme 可覆盖任意内部变量

---

components/radio-button/radio-button.tsx
components/radio-button/style/index.less
components/radio-group/const.ts
components/radio-group/radio-group.vue
components/radio-group/style/index.less
docs/.vitepress/components/radio/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: 单选按钮组新增设置支持占满父元素,子按钮平分空间

---

components/dropdown/dropdown.tsx

fix: 修复 dropdown 事件穿透问题

---

components/date-picker/calendar.vue
components/date-picker/style/index.less
components/date-picker/style/index.ts

fix: 修复 date-picker input 样式权重问题

---

components/tree/useCheck.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 修复Tree组件中父子节点不关联时选中逻辑问题

---

components/radio-group/radio-group.vue

fix: radio-group emits声明

---

components/table/style/index.less

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Table): 修复有垂直分割线+拖拽宽度时的样式问题

---

components/form/interface.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [ ] No

fix: 修改 FForm rules ts 类型

---

components/select-tree/selectTree.vue
components/select/select.vue
docs/.vitepress/components/selectTree/common.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(select-tree): 修正下拉宽度变更

---

components/select-tree/selectTree.vue
components/tree/helper.ts
components/tree/tree.tsx
components/tree/useCheck.ts
docs/.vitepress/components/selectTree/index.md
docs/.vitepress/components/selectTree/withPath.vue
pnpm-lock.yaml

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

Feat select tree path

---

components/table/column.tsx
components/table/useTableColumn.ts

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [ ] No

fix: table column id重复

---

components/drawer/drawer.tsx
components/drawer/style/index.less
components/drawer/useResizable.ts
docs/.vitepress/components/drawer/index.md
docs/.vitepress/components/drawer/resizable.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: drawer resizable可拖拽宽高度开发

---

components/table/table.tsx
components/table/useTableLayout.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: table组件宽度跟随容器宽度自适应

---

components/image/image.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 修复image图片src变更,loading状态未重置问题

---

components/input/input.vue
docs/.vitepress/components/input/autofocus.vue
docs/.vitepress/components/input/event.vue
docs/.vitepress/components/input/index.md

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No
#366 

docs: input输入框组件补充文档，及增加聚焦和失焦案例

---

components/image/image.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 修复图片加载load顺序可能异常的问题

---

components/_util/utils.ts
components/form/form.vue
components/form/formItem.vue
components/scrollbar/scrollbar.vue
components/scrollbar/useScrollbar.ts
docs/.vitepress/components/space/customSize.vue
docs/.vitepress/components/space/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

refactor: 公共方法depx和pxfy逻辑优化

---

components/input/style/index.less
components/input/style/inputInner.less

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 修复input组件字体样式不是默认字体的问题

---

components/date-picker/datePicker.vue

fix: 修复 date-picker placeholder 属性遍历导致的问题

---

components/date-picker/datePicker.vue

fix: 修复 datePicker build

---

components/config-provider/useLocale.ts
docs/.vitepress/components/configProvider/changeLocale.vue
docs/.vitepress/components/configProvider/customLocale.vue
docs/.vitepress/components/configProvider/index.md

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 多语言支持兼容未配置导致取值异常的情况

---

docs/.vitepress/config.js
package.json
pnpm-lock.yaml

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

docs: 升级vitepress及文档侧边栏体验优化

---

components/steps/step.tsx
components/steps/style/index.less
docs/.vitepress/components/steps/common.vue
docs/.vitepress/components/steps/vertical.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: steps组件，步骤描述为空时展示样式优化

---

components/_util/use/useModel.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: select multiple 支持 null

---

components/_style.ts
components/components.ts
components/text/__tests__/text.js
components/text/index.ts
components/text/interface.ts
components/text/props.ts
components/text/style/index.less
components/text/style/index.ts
components/text/style/mixin.less
components/text/text.tsx
docs/.vitepress/components/text/basic.vue
docs/.vitepress/components/text/extend.vue
docs/.vitepress/components/text/index.md
docs/.vitepress/configs/sidebar/index.js

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: 文本组件

---

components/icon/IconWrapper.tsx
docs/.vitepress/components/divider/vertical.vue
docs/.vitepress/components/icon/common.vue
docs/.vitepress/components/icon/custom.vue
docs/.vitepress/components/icon/index.md
docs/.vitepress/components/icon/loading.vue

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No
#369 

docs: 增加icon使用案例

---

docs/.vitepress/configs/navbar/index.js

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No
#387 

docs: 导航栏增加版本及相关生态链接

---

components/text/interface.ts
components/text/props.ts
components/text/style/index.less
components/text/text.tsx
docs/.vitepress/components/text/effect.vue
docs/.vitepress/components/text/index.md
docs/.vitepress/components/text/mixin.vue
docs/.vitepress/components/text/size.vue
docs/.vitepress/components/text/tag.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: text组件增加size配置项

---

components/date-picker/const.ts
components/date-picker/datePicker.vue
components/date-picker/useCalendar.ts
components/date-picker/useRange.ts
docs/.vitepress/components/datePicker/someDisabled.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#400 

fix: 修复日期范围，重新选择未重新赋值的问题

---

components/pagination/simpler.tsx

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#396 

feat: 分页器simple模式可输入跳转

---

components/pagination/style/index.less
docs/.vitepress/components/pagination/simple.vue

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

docs: 完善分页组件simple模式案例

---

docs/.vitepress/theme/components/componentDoc.vue

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

docs: 文档组件play点击防重处理

---

docs/.vitepress/components/pagination/simple.vue

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

docs: 规范组件日志打印格式

---

docs/.vitepress/config.js
docs/.vitepress/scripts/pwa.js
package.json
pnpm-lock.yaml

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No
#399 

docs: 文档构建支持pwa

---

docs/.vitepress/components/grid/align.vue
docs/.vitepress/components/grid/common.vue
docs/.vitepress/components/grid/flex.vue
docs/.vitepress/components/grid/gutterX.vue
docs/.vitepress/components/grid/gutterY.vue
docs/.vitepress/components/grid/index.md
docs/.vitepress/components/grid/justify.vue
docs/.vitepress/components/grid/offset.vue
docs/.vitepress/components/grid/order.vue
docs/.vitepress/components/grid/responsive.vue

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No
#414 

docs: 规范组件名使用,修复play下样式不生效问题

---

docs/.vitepress/scripts/pwa.js

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

docs: pwa优化，支持大文件缓存

---

components/timeline/const.ts
components/timeline/props.ts
components/timeline/timeline.tsx
components/timeline/utils.ts

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

refactor: fix timeline build 类型error

---

components/timeline/icon.tsx
components/timeline/style/index.less
components/timeline/timeline.tsx

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

refactor(timeline): 优化代码结构

---

.github/workflows/cr.yml
.github/workflows/docs.yml
.github/workflows/release-tag.yml

-   [ ] Bugfix
-   [ ] Docs
-   [x] Build-related changes
-   [ ] Yes
-   [x] No

build(workflows): yml相关配置规范

---

components/layout/aside.vue
components/layout/style/index.less
components/scrollbar/bar.vue
components/scrollbar/const.ts
components/scrollbar/scrollbar.vue
docs/.vitepress/components/layout/asideRight.vue
docs/.vitepress/components/scrollbar/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: scrollbar 支持自定义 thumb 样式 & layout aside 滚动用scrollbar

---

components/menu/const.ts
components/menu/menuItem.tsx
components/menu/style/index.less
components/menu/subMenu.tsx
components/popper/useTrigger.ts
docs/.vitepress/components/menu/collapse.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: SubMenu弹出时改为塞入body,可避免祖先overflow设置导致无法显示弹层

---

components/message/index.tsx
docs/.vitepress/components/message/close.vue
docs/.vitepress/components/message/index.md
docs/.vitepress/components/modal/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#407 

feat(message): 组件支持关闭当前消息

---

docs/.vitepress/components/empty/index.md

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

docs: 优化empty文档描述

---

components/empty/empty.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

style(empty): 修复empty自定义描述样式

---

components/input/style/index.less
components/input/style/mixin.less

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#442 

feat(input): textarea滚动条样式美化

---

components/scrollbar/bar.vue
components/scrollbar/style/index.less

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#449 

feat(scrollbar): 滚动条样式体验优化

---

components/table/components/bodyTable.tsx
components/table/components/noData.tsx
components/table/style/index.less
components/table/table.tsx
docs/.vitepress/components/table/nodata.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#440 

feat(table): 无数据场景交互优化及丰富组件文档无数据的案例

---

docs/.vitepress/components/empty/index.md
docs/.vitepress/components/scrollbar/index.md
docs/.vitepress/components/scrollbar/maxHeight.vue
docs/.vitepress/components/scrollbar/more.vue
docs/.vitepress/components/scrollbar/native.vue
docs/.vitepress/components/timeline/descPosition.vue
docs/.vitepress/components/timeline/direction.vue
docs/.vitepress/components/timeline/titlePosition.vue

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

docs: scrollbar补充组件文档案例 及 timeline和empty组件文档规范

---

components/modal/modal.tsx
components/modal/modalApi.tsx
docs/.vitepress/components/modal/asyncSubmit.vue
docs/.vitepress/components/modal/common.vue
docs/.vitepress/components/modal/confirm.vue
docs/.vitepress/components/modal/customFooter.vue
docs/.vitepress/components/modal/customTitle.vue
docs/.vitepress/components/modal/feedback.vue
docs/.vitepress/components/modal/index.md
docs/.vitepress/components/modal/showCancel.vue
docs/.vitepress/configs/sidebar/index.js

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No
#441 #438 

feat(modal): 支持按钮loading状态、标题type类型、是否展示取消按钮配置项，及组件文档案例完善

---

components/scrollbar/scrollbar.vue
docs/.vitepress/components/scrollbar/horizontal.vue
docs/.vitepress/components/scrollbar/index.md
docs/.vitepress/components/scrollbar/scrollbar.vue

feat: scrollbar 支持 scrollToEnd 方法

---

components/scrollbar/style/index.less

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#460 

feat(scrollbar): hover交互体验优化

---

docs/.vitepress/components/checkbox/index.md
docs/.vitepress/components/radio/index.md
docs/.vitepress/components/select/index.md

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No
#454 

docs: 补充组件配置项说明

---

components/drawer/drawer.tsx
components/drawer/style/index.less
components/drawer/useResizable.ts
docs/.vitepress/components/drawer/asyncSubmit.vue
docs/.vitepress/components/drawer/common.vue
docs/.vitepress/components/drawer/customFooter.vue
docs/.vitepress/components/drawer/customTitle.vue
docs/.vitepress/components/drawer/index.md

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No
#439 

feat(drawer): 增加确认按钮 loading 状态及是否展示取消按钮配置项 (#455)

---

components/drawer/drawer.tsx
components/drawer/useResizable.ts
docs/.vitepress/components/drawer/resizable.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#466 

fix(drawer): 修复不同位置打开抽屉，拖拽不生效的问题

---

components/select/select.vue
docs/.vitepress/components/select/filterable.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#477 

fix(select): 解决清空操作，过滤列表缓存的问题

---

components/drawer/style/index.less
docs/.vitepress/components/drawer/common.vue

-   [x] Bugfix
-   [x] Docs
-   [ ] Yes
-   [ ] No
#474 

fix(drawer): 解决无标题情况下，关闭按钮不可点击的问题

---

components/cascader/interface.ts
components/select/interface.ts
components/tree/interface.ts

-   [x] Bugfix
-   [ ] Yes
-   [x] No

fix: select、tree、cascader 选项类型校验兼容自定义的情况

---

components/cascader/useData.ts
components/tree/useData.ts

-   [ ] Bugfix
-   [ ] Docs
-   [x] Build-related changes
-   [ ] Yes
-   [x] No

chore: 修复构建时类型报错问题

---

components/form/formItem.vue
docs/.vitepress/components/form/asyncValidator.vue
docs/.vitepress/components/form/index.md
package.json
pnpm-lock.yaml

-   [x] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No
#471 

fix(Form): 异步表单校验支持

---

docs/.vitepress/components/button/basic.vue
docs/.vitepress/components/button/disabled.vue
docs/.vitepress/components/button/index.md
docs/.vitepress/components/button/loading.vue
docs/.vitepress/components/button/long.vue
docs/.vitepress/components/button/other.vue
docs/.vitepress/components/button/size.vue
docs/.vitepress/components/button/type.vue

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

docs(Button): 文档案例交互优化

---

components/form/formItem.vue
components/form/style/index.less
docs/.vitepress/components/form/asyncValidator.vue
docs/.vitepress/components/form/complexValidate.vue
docs/.vitepress/components/form/index.md
docs/.vitepress/components/form/nestValidator.vue
docs/.vitepress/components/form/validate.vue

-   [x] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No
#498 

fix(Form): 修复表单嵌套时必填项样式设置的问题

---

components/table/components/td.tsx
components/table/style/index.less

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#500 

feat(Table): 展开行图标，修改及增加hover态交互反馈

---

components/table/components/bodyTable.tsx
components/table/style/index.less
components/table/table.tsx
components/table/useTableStyle.ts
docs/.vitepress/components/table/common.vue
docs/.vitepress/components/table/index.md

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No
#457 
#446 

feat(Table): 增加 hover行样式、斑马线条纹 配置项

---

components/drawer/style/index.less
components/modal/style/index.less
docs/.vitepress/components/modal/common.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#503 

fix(Modal): 解决无标题情况下，关闭按钮不可点击的问题

---

components/_util/interface.ts
components/checkbox-group/checkbox-group.vue
components/checkbox-group/const.ts
components/radio-group/const.ts
components/radio-group/radio-group.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: checkbox和radio支持option为null & option类型修复

---

components/locales/lang/enUS.ts
components/locales/lang/zhCN.ts
components/select-cascader/const.ts
components/select-cascader/selectCascader.vue
components/select-cascader/style/index.ts
components/select/const.ts
components/select/select.vue
docs/.vitepress/components/select/multiple.vue
docs/.vitepress/components/selectCascader/disabled.vue
docs/.vitepress/components/selectCascader/emitPath.vue
docs/.vitepress/components/selectCascader/filterable.vue
docs/.vitepress/components/selectCascader/index.md
docs/.vitepress/components/selectTree/withPath.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#508 

feat(Cascader): 支持本地数据项搜索

---

components/form/formItem.vue
components/form/interface.ts
docs/.vitepress/components/form/align.vue
docs/.vitepress/components/form/index.md

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

feat(Form): 表单组件增加对齐方式 align 配置项

---

components/steps/step.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 可能是vue-jsx的bug,当title从对象变成字符串,会渲染异常

---

components/_util/use/useModel.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 修复组件使用useArrayModel做双向绑定,在组件外重置双向绑定属性为undefined无效

---

components/input/input.vue
docs/.vitepress/components/input/autofocus.vue
docs/.vitepress/components/input/clearable.vue
docs/.vitepress/components/input/event.vue
docs/.vitepress/components/input/index.md
docs/.vitepress/components/input/password.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#516 

fix(Input): 修复clear事件不触发的问题

---

.eslintrc.js
tsconfig.base.json
tsconfig.eslint.json
tsconfig.json

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

build(tsconfig.json): 配置文件优化

---

components/form/interface.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#532 

fix(FormItem): value类型不识别问题修复

---

components/upload/trigger.vue
docs/.vitepress/components/upload/common.vue
docs/.vitepress/components/upload/customerUpload.vue
docs/.vitepress/components/upload/default.vue
docs/.vitepress/components/upload/drag.vue
docs/.vitepress/components/upload/fileList.vue
docs/.vitepress/components/upload/initList.vue
docs/.vitepress/components/upload/previewUpload.vue
docs/.vitepress/components/upload/singleUpload.vue

-   [x] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No
#536 

fix(Upload): 重复上传文件，change事件可能不触发

---

components/collapse/collapse.vue
components/collapse/common.ts
docs/.vitepress/components/collapse/arrowleft.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(collapse): arrow无法响应式更新

---

.github/workflows/docs.yml

-   [ ] Bugfix
-   [x] Docs
-   [x] Build-related changes
-   [ ] Yes
-   [x] No

build(docs): npm安装依赖，文档构建失败，改为pnpm

---

components/_util/use/useModel.ts
components/calendar/useCalendarData.ts
components/checkbox-group/const.ts
components/checkbox-group/interface.ts
components/collapse/collapse.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

refactor(useModel): useNormalModel, useArrayModel 函数增加类型

---

components/space/const.ts
components/space/index.ts
components/space/props.ts
components/space/space.tsx
docs/zh/guide/quick-start.md

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Space): 垂直间距补偿值计算问题修复

---

components/table/components/header.tsx
components/table/components/td.tsx
components/table/useTableStyle.ts
docs/.vitepress/components/table/heightAndFixed.vue
docs/.vitepress/components/table/multiHeader.vue

-   [x] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No
#540 

fix(Table): 多级表头固定样式异常修复

---

components/_util/interface.ts
components/_util/use/useModel.ts
components/layout/aside.vue
components/pagination/pager.tsx
components/select-cascader/selectCascader.vue
components/select-tree/selectTree.vue
components/select/select.vue
components/table/column.tsx
components/table/useTableExpand.ts
components/table/useTableSelect.ts
components/tabs/interface.ts
components/tabs/tabs.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 修复多个组件中类型错误问题

---

components/table/style/index.less
components/table/useTableStyle.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Table): 修复仅单侧固定列时，对侧滚动阴影丢失问题

---

components/drawer/const.ts
components/drawer/drawer.tsx
components/drawer/style/index.less
components/drawer/useResizable.ts

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(Drawer): 修改抽屉拖拽样式，调整最大拖拽尺寸限制

---

components/time-picker/time-picker.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(TimePicker): 设置了 step 相关属性时，不展示「此刻」快捷按钮

---

components/table/components/header.tsx
components/table/style/index.less
components/table/useTable.ts
components/table/useTableColumn.ts
components/table/useTableStyle.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Table): 修复 verticalLine 打开时，多级表头的部分 th 右边框显示问题

---

components/drawer/drawer.tsx
components/drawer/props.ts
components/drawer/style/index.less
docs/.vitepress/components/drawer/index.md
docs/.vitepress/components/drawer/operable.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: 抽屉组件新增无蒙层下,交互其他ui能力

---

components/drawer/style/index.less
docs/.vitepress/components/drawer/index.md
docs/.vitepress/components/drawer/operable.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: demo更新,文档文案修改,增加鼠标不可点击样式

---

docs/.vitepress/components/timeline/index.md

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

docs(Timeline): 修改引用 demo 写法，修复 demo 匹配错误问题

---

components/dropdown/dropdown.tsx
components/dropdown/index.ts
components/dropdown/props.ts
components/dropdown/style/index.less
docs/.vitepress/components/dropdown/index.md

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Dropdown): 显示选中选项时，预留选中图标空间

---

components/date-picker/useCalendar.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(DatePicker): datetimerange 模式中时间更新直接触发更新，与 selectedStatus 解耦

---

components/drawer/drawer.tsx
components/drawer/props.ts
components/drawer/useResizable.ts
docs/.vitepress/components/drawer/index.md
docs/.vitepress/components/drawer/operable.vue
docs/.vitepress/components/drawer/resizable.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#567

feat(Drawer): 支持配置可拖拽范围

---

components/drawer/drawer.tsx
components/drawer/props.ts
components/drawer/useDimension.ts
components/drawer/useResizable.ts
docs/.vitepress/components/drawer/index.md
docs/.vitepress/components/drawer/resizable.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(Drawer): 新增 dimension 属性替代 height 和 width, 后两者标为废弃

---

components/tabs/tabs.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Tabs): 修复滚动内阴影展示计算问题

---

components/tabs/tabs.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Tabs): 修复 Card 模式样式问题

---

components/modal/index.ts
components/modal/modal.tsx
components/modal/modalApi.tsx
components/modal/props.ts
components/modal/style/index.ts
components/modal/useBodyMaxHeight.ts
docs/.vitepress/components/modal/customHeight.vue
docs/.vitepress/components/modal/index.md
docs/.vitepress/components/modal/maxHeight.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

Feat modal组件新增height配置项

---

components/input/input.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(input): 修复当input未设置modelValue时输入autosize不生效问题

---

components/table/style/index.less
docs/.vitepress/components/table/nodata.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Table): 无数据组件 border 样式修复

---

components/tabs/style/index.less

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Tabs): 移除 pane-wrapper 中的 white-space ，会影响容器内子元素的默认样式

---

docs/.vitepress/components/tabs/extend.vue

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

docs(Tabs): 优化前缀、后缀 demo

---

components/image/preview.vue
components/image/useDrag.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Image): 修复 preview 拖拽、缩放动画延迟问题

---

components/date-picker/useCalendar.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(DatePicker): 修复 type 由 year 切换至其他时，内部 calendar 渲染异常

---

components/tree/interface.ts
components/tree/props.ts
components/tree/style/index.less
components/tree/tree.tsx
components/tree/treeNode.tsx
components/tree/useCurrentData.ts
components/tree/useData.ts
components/tree/useDrag.ts
docs/.vitepress/components/tree/drag.vue
docs/.vitepress/components/tree/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: Tree拖拽支持inside

---

components/table/components/bodyTable.tsx
components/table/components/headerTable.tsx
components/table/style/index.less
components/table/useTableColumn.ts
components/table/useTableStyle.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Table): 固定表头水平滚动时，增加表头的内阴影

---

components/table/column.tsx
components/table/components/header.tsx
components/table/components/td.tsx
components/table/interface.ts
components/table/useTableSelect.ts
docs/.vitepress/components/table/checkbox.vue
docs/.vitepress/components/table/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(Table): 新增table组件单选行功能

---

docs/.vitepress/theme/components/exampleRepl.vue

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

docs: Playground 抽屉支持拖拽

---

components/select/optionList.tsx
components/select/props.ts
components/select/select.vue
docs/.vitepress/components/select/index.md
docs/.vitepress/components/select/virtualScroll.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(Select): 虚拟滚动可配置开启

---

components/descriptions/constants.ts
components/descriptions/descriptions.tsx
components/descriptions/descriptionsItem.tsx
components/descriptions/index.ts
components/descriptions/interface.ts
components/descriptions/props.ts
components/descriptions/style/index.less
docs/.vitepress/components/descriptions/borded.vue
docs/.vitepress/components/descriptions/index.md

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Descriptions): 优化 Item 的 span 计算逻辑

---

components/table/components/noData.tsx
components/table/table.tsx

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(Table): 无数据文案支持国际化

---

components/tree/style/index.less
components/tree/treeNode.tsx
components/tree/useDrag.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 修复Tree拖拽到最后一位会导致滚动 & 拖拽到Tree之外还有拖拽位置效果

---

components/select/select.vue
components/select/style/index.less
docs/.vitepress/components/select/addon.vue
docs/.vitepress/components/select/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(Select): 增加顶部插槽 header 配置项

---

components/rate/rate.tsx
docs/.vitepress/components/rate/basic.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Rate): rate空星渲染方式修正

---

components/descriptions/descriptionsItem.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Description): VNode解析报错修复

---

components/descriptions/descriptionsItem.tsx
docs/.vitepress/components/descriptions/borded.vue
docs/.vitepress/components/descriptions/index.md

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Description): 修复 Item 注册逻辑, 移除 span 相关告警提示

---

components/select-trigger/interface.ts
components/select-trigger/selectTrigger.vue
components/select-trigger/style/index.less

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(SelectTrigger): 折叠的 Tag 增加弹出框展示

---

components/table/useResize.ts

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
相关提交：4423dc5

refactor(Table): 优化 headerResize 相关参数命名、类型定义

---

components/collapse/collapse.vue
components/collapse/collapseExpose.ts
docs/.vitepress/theme/components/playground.js
package.json

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

refactor(Collapse): 移除无用的 emits 定义

---

components/drawer/drawer.tsx
components/drawer/style/index.less
docs/.vitepress/components/drawer/operable.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Drawer): 更新光标逻辑，有蒙层可以点击蒙层关闭展示常规光标

---

docs/postcss.config.mjs
package.json
pnpm-lock.yaml
scripts/genComponentDoc.mjs
tsconfig.eslint.json

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

docs: vitepress相关更新还原

---

components/drawer/drawer.tsx
components/drawer/useDimension.ts
components/drawer/useResizable.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Drawer): 尺寸补充支持百分数

---

components/drawer/drawer.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Drawer): 修复尺寸赋值 style 单位问题

---

components/input/input.vue
components/input/style/index.less
docs/.vitepress/components/input/append.vue
docs/.vitepress/components/input/number.vue
docs/.vitepress/components/input/textarea.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Input): word limit 样式优化

---

components/input/input.vue
components/table/column.tsx
components/table/table.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 修复 ExtractPublicPropTypes 推导组件 Props 类型问题

---

components/tabs/props.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Tabs): 移除 props 中的 key 配置项，由于是 vue 的保留字段

---

docs/.vitepress/components/message/index.md

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

docs(Message): 修改 demo 引入写法

---

components/popper/popper.tsx
components/popper/props.ts
docs/.vitepress/components/tooltip/common.vue
docs/.vitepress/components/tooltip/index.md
docs/.vitepress/components/tooltip/trigger.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(Popper): 新增 popperStyle prop

---

components/_util/constants.ts
components/carousel/indicator.tsx
components/checkbox/checkbox.vue
components/radio/radio.vue
components/scrollbar/const.ts
components/table/components/cell.tsx
components/table/components/virtualTable.tsx
package.json
pnpm-lock.yaml
scripts/build-types.mjs

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 修复因 vue 版本升级引起的类型报错

---

components/cascader/cascaderNode.tsx
components/checkbox/checkbox.vue
components/radio/radio.vue
components/table/components/header.tsx
components/table/components/td.tsx
components/tree/treeNode.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 修复 FCheckbox 和 FRadio 的 onClick 为 onChange

---

components/_style.ts
components/components.ts
components/progress/components/CircleProgress.tsx
components/progress/components/LineProgress.tsx
components/progress/const.ts
components/progress/helper.ts
components/progress/index.ts
components/progress/progress.tsx
components/progress/props.ts
components/progress/style/index.less
components/progress/style/index.ts
docs/.vitepress/components/progress/base.vue
docs/.vitepress/components/progress/index.md
docs/.vitepress/components/progress/textSlot.vue
docs/.vitepress/configs/sidebar/index.ts

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(Progress): 新增进度条组件

---

.github/workflows/docs.yml
components/_util/interface.ts
components/_util/types.ts
components/avatar/props.ts
components/avatarGroup/props.ts
components/badge/props.ts
components/calendar/props.ts
components/carousel/carousel.tsx
components/carousel/const.ts
components/rate/props.ts
components/table/useTableExpand.ts
components/table/useTableSelect.ts
components/timeline/utilTypes.ts
components/timeline/utils.ts
docs/.vitepress/theme/components/exampleRepl.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

refactor(components): 整理工具类型

---

components/select-trigger/selectTrigger.vue
components/select/select.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Select): disabled 判断逻辑修正，样式与交互一致

---

components/table/components/cell.tsx
docs/.vitepress/components/table/common.vue

fix(Table): 列值为 object 类型时，会导致组件渲染异常

---

.vscode/settings.json
components/tree/interface.ts
components/tree/treeNode.tsx
components/tree/useData.ts
docs/.vitepress/components/tree/index.md

feat(Tree): label 支持 VNode

---

components/_util/interface.ts
components/_util/use/useSelect.ts
components/checkbox-group/checkbox-group.vue
components/checkbox-group/const.ts
components/checkbox-group/index.ts
components/checkbox-group/interface.ts
components/checkbox-group/props.ts
components/checkbox-group/useCheckboxGroup.ts
components/checkbox/checkbox.vue
components/checkbox/index.ts
components/checkbox/props.ts
components/radio-button/index.ts
components/radio-button/props.ts
components/radio-button/radio-button.tsx
components/radio-group/const.ts
components/radio-group/index.ts
components/radio-group/props.ts
components/radio-group/radio-group.vue
components/radio-group/useRadioGroup.ts
components/radio/index.ts
components/radio/props.ts
components/radio/radio.vue
components/transfer/checkbox.tsx
components/transfer/index.ts
docs/.vitepress/components/checkbox/index.md

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Radio, Checkbox): 修复在 Group 组件内无法触发 change 事件的问题

---

components/rate/props.ts
components/rate/rate.tsx
components/rate/useRate.ts
docs/.vitepress/components/rate/index.md

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
https://github.com/WeBankFinTech/fes-design/issues/642

fix(Rate): 修复未传入 v-model 的情况

---

components/tabs/constants.ts
components/tabs/helper.ts
components/tabs/style/index.less
components/tabs/tab.tsx
components/tabs/tabs.tsx
docs/.vitepress/components/tabs/common.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Tabs): 滚动条复用 Scrollbar 组件，同时修复 Win 下横向滚动问题

---

components/select-tree/selectTree.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(SelectTree): 修复 TreeOption 的 label 为自定义渲染时，过滤函数的逻辑

---

components/tabs/tabs.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Tabs): 修复 displayDirective="show" 渲染错误的问题

---

components/modal/modal.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Modal): 修复 modal 蒙层关闭逻辑

---

components/radio-group/style/index.less
docs/.vitepress/components/radio/button.vue
docs/.vitepress/components/radio/index.md

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Radio): 修复按钮组仅有一项时样式错误

---

components/_util/use/useEsc.ts
components/drawer/drawer.tsx
components/drawer/props.ts
components/modal/modal.tsx
components/modal/props.ts
docs/.vitepress/components/drawer/closable.vue
docs/.vitepress/components/drawer/index.md
docs/.vitepress/components/modal/closable.vue
docs/.vitepress/components/modal/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: Drawer 和 Modal 添加 Esc 快捷关闭配置项

---

components/select/optionList.tsx
components/select/style/index.less
docs/.vitepress/components/select/common.vue

-   [x] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No
#685 

fix(FSelect): 选项值选中时，提示信息会闪跳

---

components/table/useTableLayout.ts
docs/.vitepress/components/table/height.vue

-   [x] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

fix(Table): 修复 table 在数据行数变更的时候,高度异常问题

---

components/table/components/td.tsx
components/table/style/index.less
docs/.vitepress/components/table/span.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Table): 修复合并单元格时边框样式错误问题

---

components/popper/usePopper.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#684 

fix(Tooltip): 修复触发元素隐藏后，提示信息动画执行异常的问题

---

components/table/components/colgroup.tsx
components/table/components/header.tsx
components/table/useResize.ts
components/table/useTableLayout.ts
components/table/useTableStyle.ts

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

refactor(Table): 优化变量命名

---

components/_util/interface.ts
components/calendar/calendar.tsx
components/calendar/props.ts
components/timeline/props.ts
components/timeline/timeline.tsx
package.json
pnpm-lock.yaml

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(utils): 新增 slots、emit 工具类型函数

---

docs/.vitepress/components/spin/index.md

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

docs(Spin): 配置项 delay 表述优化

---

components/popper/usePopper.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Dropdown): 修复 popper 位置计算函数中的错误逻辑

---

components/drawer/style/index.less

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Drawer): 调整关闭按钮样式

---

components/upload/useUpload.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#703 

fix(Upload): 兼容 fileList 传非数组的情况

---

components/transfer/oneWayTransfer.tsx
components/transfer/style/index.less
components/transfer/twoWayTransfer.tsx
components/transfer/useOptionsFilter.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Transfer): 修复双向穿梭时，checkbox 数据更新异常

---

components/form/formItem.vue
components/form/interface.ts
docs/.vitepress/components/form/basic.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(Form): FormItem 支持自定义 content 样式

---

components/input-number/input-number.vue
docs/.vitepress/components/inputNumber/common.vue
docs/.vitepress/components/inputNumber/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(InputNumber): 增加控制显示步进箭头按钮的配置

---

components/input-number/input-number.vue
components/input/input.vue
docs/.vitepress/components/input/common.vue
docs/.vitepress/components/input/handleFocus.vue
docs/.vitepress/components/input/index.md
docs/.vitepress/components/inputNumber/common.vue
docs/.vitepress/components/inputNumber/index.md

feat(Input & InputNumber): 增加 autofocus 配置项

---

components/date-picker/style/index.less
components/input-file/style/index.less
components/input/style/index.less
components/select-trigger/style/index.less

-   [x] Bugfix
-   [x] No
#724 

fix: 修复暗黑模式下，输入框样式黑色背景的问题

---

components/modal/modal.tsx
docs/.vitepress/components/modal/common.vue
docs/.vitepress/components/modal/index.md

feat(Modal): 增加 onAfterEnter 和 onAfterLeave 事件回调

---

components/drawer/drawer.tsx
components/drawer/props.ts
docs/.vitepress/components/drawer/common.vue
docs/.vitepress/components/drawer/index.md
docs/.vitepress/components/modal/common.vue

-   [x] Docs
-   [ ] Yes
-   [x] No
#729 

feat(Drawer): 增加 onAfterEnter 和 onAfterLeave 事件回调

---

components/drawer/drawer.tsx
components/drawer/props.ts
components/modal/modal.tsx
components/modal/props.ts
docs/.vitepress/components/drawer/index.md
docs/.vitepress/components/modal/index.md

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

feat(Modal&Drawer): modal,drawer组件新增wrapperClass配置

---

components/menu/style/index.less

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(Menu): 补充垂直方向时，菜单项选中样式

---

components/form/style/index.less

feat(FormItem): label 文字颜色设置为默认文字颜色，兼容跟随系统样式

---

components/_util/use/useResize.ts

fix: 修复 useResize 元素无法监听的报错情况

---

components/ellipsis/ellipsis.tsx
docs/.vitepress/components/ellipsis/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(Ellipsis): 增加默认 Tooltip 样式

---

components/breadcrumb/index.ts
docs/.vitepress/components/breadcrumb/index.md

-   [x] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

fix(Breadcrumb): 面包屑组件命名问题,补充文档

---

components/table/table.tsx
components/table/useTableSort.ts
docs/.vitepress/components/table/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(Table): 增加 afterSort 事件

---

components/table/useTableStyle.ts
components/transfer/interface.ts
components/transfer/props.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Table, Transfer): 解决 build:esm-browser 报错循环依赖问题

---

components/select-trigger/selectTrigger.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(SelectTrigger): 折叠的 Tag 弹出框增加滚动条

---

docs/zh/guide/quick-start.md

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

docs: 组件引入增加相关代码示例

---

components/draggable/draggable.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: draggable插槽改名

---

components/date-picker/rangeInput.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(DatePicker): 修复 RangeInput 处理 againFocusFlag 逻辑

---

.husky/commit-msg
.husky/pre-commit

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

refactor: husky 配置完善

---

scripts/build-types.js

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

refactor: build-types 引入mjs修复

---

components/table/components/cell.tsx
docs/.vitepress/components/table/customContent.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(TableColumn): formatter 支持返回 VNode

---

commitlint.config.cjs

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

refactor(commitlint): config update

---

components/menu/const.ts
components/menu/subMenu.tsx
docs/.vitepress/components/menu/customContainer.vue
docs/.vitepress/components/menu/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(Menu): 支持 popper 的 getContainer

---

components/date-picker/useCalendar.ts
components/table/column.tsx
components/table/components/cell.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#768 

fix(Table): 修复 Column 的 CellProps 导出类型不对的问题

---

components/cascader/cascader.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Cascader): 处理 data 置空时，已展开的 Menus 不会重置的问题

---

components/_style.ts
components/components.ts
components/text-highlight/index.ts
components/text-highlight/props.ts
components/text-highlight/style/index.less
components/text-highlight/style/index.ts
components/text-highlight/text-highlight.tsx
components/text/style/index.less
components/text/text.tsx
docs/.vitepress/components/text-highlight/base.vue
docs/.vitepress/components/text-highlight/index.md
docs/.vitepress/components/text/index.md
docs/.vitepress/configs/sidebar/index.ts

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

feat(TextHighlight): 新增 TextHighlight 文本高亮组件

---

docs/.vitepress/components/text-highlight/base.vue

-   [x] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

docs: 修复 demo 样式污染文档的问题

---

components/_util/utils.ts
components/text/interface.ts
components/text/props.ts
components/text/text.tsx
docs/.vitepress/components/text/gradient.vue
docs/.vitepress/components/text/index.md

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

feat(Text): 文本组件新增 gradient 属性

---

components/modal/modalApi.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Modal): 补齐 Modal API 参数类型中缺失的字段

---

components/avatarGroup/avatarGroup.tsx
components/avatarGroup/props.ts
components/calendar/props.ts
components/table/useTableSort.ts
components/timeline/props.ts
eslint.config.js

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

build(eslint): 调整规则，修复 build:type 脚本报错

---

components/text/style/index.less
components/text/text.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Text): 处理text组件渐变样式失效的问题

---

components/text-highlight/props.ts
components/text-highlight/text-highlight.tsx
docs/.vitepress/components/text-highlight/base.vue
docs/.vitepress/components/text-highlight/index.md
docs/.vitepress/components/text-highlight/markTextStyle.vue

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

feat(TextHighlight): 高亮组件新增自定义样式

---

components/draggable/draggable.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#789 

fix(Draggable): 修复 tag 变量识别为原生标签的问题

---

components/menu/const.ts
components/menu/interface.ts
components/menu/menu.tsx
components/menu/subMenu.tsx
components/menu/useChildren.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Menu): 修复 mode 和 trigger 配置项传字符串，类型报错提示的问题

---

components/radio-button/radio-button.tsx
components/radio-button/style/index.less
docs/.vitepress/components/radio/iconSlot.vue
docs/.vitepress/components/radio/index.md

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

feat(RadioButton): 单选按钮组增加 icon slot

---

components/form/index.ts
components/form/interface.ts

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(Form): 调整 props.rules 类型定义，并导出 Rules 类型

---

components/table/useTableSelect.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Table): 修复初始化 checkedKeys 被清空逻辑异常问题

---

components/_theme/base.ts

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#803 

feat: 分隔线颜色样式优化

---

components/_style.ts
components/_theme/base.ts
components/components.ts
components/link/index.ts
components/link/link.tsx
components/link/props.ts
components/link/style/index.less
components/link/style/index.ts
docs/.vitepress/components/link/base.vue
docs/.vitepress/components/link/href.vue
docs/.vitepress/components/link/icon.vue
docs/.vitepress/components/link/index.md
docs/.vitepress/configs/sidebar/index.ts

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

feat(Link)：新增链接组件

---

components/input/inputInner.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: input slot.suffix可响应式

---

components/breadcrumb/breadcrumb-item.tsx
components/breadcrumb/breadcrumb.tsx
components/breadcrumb/style/index.less
docs/.vitepress/components/breadcrumb/base.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#810 

fix(BreadCrumbItem): 支持 v-for 渲染

---

components/link/link.tsx
components/link/props.ts
components/link/style/index.less
docs/.vitepress/components/link/base.vue
docs/.vitepress/components/link/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#813 

feat(Link): 组件交互及样式优化

---

components/select/optionList.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 虚拟滚动下，value值不存在时选项不渲染问题

---

components/date-picker/calendars.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#821 

fix(DatePicker): 修复日期范围选择组件，底部操作栏点击面板会触发面板隐藏的问题

---

components/float-pane/float-pane.tsx

fix: 让 float pane 可控制

---

components/float-pane/float-pane.tsx

fix: float pane 完全受控

---

components/empty/empty.vue
components/empty/style/empty.less
docs/.vitepress/components/empty/bottom.vue
docs/.vitepress/components/empty/customImageAttr.vue
docs/.vitepress/components/empty/customImageSlot.vue
docs/.vitepress/components/empty/index.md
docs/.vitepress/components/empty/select.vue
docs/.vitepress/components/empty/size.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#819 

fix(Empty): 支持自定义图片和描述插槽

---

components/select-tree/selectTree.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [ ] No

fix(SelectTree): 默认过滤函数兼容自定义 label 字段

---

components/link/style/index.less
docs/.vitepress/components/link/href.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#827 

feat(Link): 解决嵌套a标签样式冲突的问题

---

components/image/preview.vue
components/image/style/index.less
components/image/useDrag.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Image): preview 增加拖拽样式

---

components/table/useTableStyle.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Table): 修复无数据时，固定表头无法滚动的问题

---

docs/.vitepress/components/collapse/accordion.vue

-   [x] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

docs(Collapse): 修复 demo 报错

---

components/form/formItem.vue
components/form/interface.ts
docs/.vitepress/components/form/disabled.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(Form): 支持配置 FormItem 的 disabled

---

components/form/style/index.less

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Form): labelPosition: top 时，优化 label 样式

---

components/card/card.vue
components/card/style/index.less
docs/.vitepress/components/card/customFooter.vue
docs/.vitepress/components/card/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(Card): 增加 footer

---

components/table/useTableColumn.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#838 

fix(Table): 修复 columns 配置项为 null 时渲染异常的问题

---

components/select/props.ts
components/select/select.vue
docs/.vitepress/components/select/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(Select): 增加 Trigger 单独的 class、style 配置

---

components/tree/props.ts
components/tree/tree.tsx
components/tree/treeNode.tsx
components/tree/useData.ts
docs/.vitepress/components/tree/async.vue
docs/.vitepress/components/tree/common.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Tree): 优化顶层 node 的 no expand 逻辑

---

components/form/formItem.vue
docs/.vitepress/components/form/formItemValidator.vue
docs/.vitepress/components/form/index.md

-   [x] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No
#844 

fix(FormItem): 修复value配置项校验异常的问题

---

components/_util/use/useModel.ts
components/select/select.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#846 

fix(Select): 修复model重复赋值为undefined报错的问题

---

components/tree/useCurrentData.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Tree): 修复 remote 模式 expandedKeys 变化时，没有正确修改 node.isExpanded

---

components/menu/menu.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#853 

fix(FMenu): 修复垂直模式下, 折叠的时候, 子菜单重叠展示的问题

---

components/menu/subMenu.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(FMenu): 保证同级菜单项展开时可交互

---

components/table/components/bodyTable.tsx
components/table/useTableStyle.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Table): 是否固定表头、是否展示 NoData 时，重置滚动状态

---

components/tag/style/index.less

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Tag): 修复不能复制标签文字的问题

---

components/menu/const.ts
components/menu/menu.tsx
components/menu/subMenu.tsx
components/popper/const.ts
components/popper/interface.ts
components/popper/popper.tsx
components/popper/useTrigger.ts
docs/.vitepress/components/menu/index.md

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#849 

refactor(FMenu): 水平模式，鼠标移除不隐藏菜单的问题相关，技术方案优化

---

components/menu/subMenu.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [ ] No
[https://github.com/WeBankFinTech/fes-design/issues/852](https://github.com/WeBankFinTech/fes-design/issues/852)

fix: 修复menu可能打开多个子菜单问题

---

docs/.vitepress/components/tabs/index.md

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

docs: tabs 文档补充

---

components/select-trigger/style/index.less

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(SelectTrigger): 修复多选模式下 input 元素宽度计算问题

---

components/tabs/style/index.less

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Tabs): 修复卡片式页签下超出容器宽度后样式异常的问题

---

docs/.vitepress/components/popper/common.vue
docs/.vitepress/components/popper/visible.vue

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No
#870 

docs(Popper): 解决控制台告警问题

---

components/table/useTableLayout.ts

-   [x] Bugfix
-   [ ] Docs
-   [x] Yes
-   [ ] No

fix(Table): 兼容 windows 浏览器滚动条导致高度有小数的场景

---

components/table/useTableStyle.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#873 

fix(Table): 修复弹窗表格初始化执行报错的问题

---

components/select-tree/selectTree.vue
components/tree/props.ts
components/tree/treeNode.tsx
docs/.vitepress/components/select/filterable.vue
docs/.vitepress/components/selectTree/filterable.vue
docs/.vitepress/components/selectTree/index.md
docs/.vitepress/components/selectTree/multiple.vue
docs/.vitepress/components/selectTree/withPath.vue
docs/.vitepress/components/tree/common.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#877 

feat(SelectTree): 增加 filterTextHighlight 过滤文本是否高亮显示的配置项

---

components/descriptions/descriptionsItem.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 修复 FDescriptionItem 异常报错

---

components/tree/treeNode.tsx
docs/.vitepress/components/tree/fix.vue
pnpm-lock.yaml

feat: tree node slot 支持 hover 参数

---

components/select/select.vue

fix: select limit 限制异常

---

docs/.vitepress/components/tree/index.md

-   [] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

docs: update tree event drop

---

docs/.vitepress/components/message/content.vue

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

docs(Message): 增加自定义消息内容点击即可关闭的实例

---

components/input-number/input-number.vue
docs/.vitepress/components/inputNumber/index.md
docs/.vitepress/components/inputNumber/maxAndMin.vue
docs/.vitepress/components/inputNumber/precision.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#895 

fix(InputNumber): 修复输入值首位数字小于最小值时导致被重置为最小值的问题

---

components/float-pane/float-pane.tsx
components/float-pane/props.ts
components/float-pane/useDrag.ts
components/pagination/simpler.tsx
docs/.vitepress/components/float-pane/common.vue
docs/.vitepress/components/float-pane/index.md
docs/.vitepress/components/pagination/simple.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(FloatPane): 增加配置项 cachePositionKey, 避免多个浮动面板共享位置缓存、增加 resetPosition 方法、增加拖拽边界检测

---

components/pagination/simpler.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Pagination): 修复 简洁型 无效分页数据无法更新的问题

---

components/popper/popper.tsx
components/popper/props.ts
components/popper/usePopper.ts
docs/.vitepress/components/popper/index.md

feat: popper 受控模式

---

components/tooltip/tooltip.tsx
docs/.vitepress/components/popper/index.md
docs/.vitepress/components/popper/passive.vue
docs/.vitepress/components/tooltip/index.md
docs/.vitepress/components/tooltip/passive.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(Tooltip): 增加受控模式

---

components/virtual-list/virtualList.tsx
docs/.vitepress/components/virtualList/vertical.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 修复虚拟滚动组件动态添加子项不能滚动问题

---

components/_util/popupManager.ts

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: zIndex 全局管理，由内存改为 sessionStorage

---

components/form/form.vue
docs/.vitepress/components/form/formItemValidator.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(Form): 支持清除和重置指定表单项

---

components/_util/popupManager.ts
components/virtual-list/virtualList.tsx
docs/.vitepress/components/virtualList/vertical.vue

-   [x] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

fix(VirtualList): 修复 Select 结合 VirtualList 时滚动到底部不正确的问题

---

components/tooltip/tooltip.tsx
docs/.vitepress/components/popper/passive.vue
docs/.vitepress/components/popper/visible.vue
docs/.vitepress/components/tooltip/confirm.vue
docs/.vitepress/components/tooltip/index.md
docs/.vitepress/components/tooltip/passive.vue

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

feat(Tooltip): confirm 模式增加是否显示确认和取消按钮的配置项

---

components/dropdown/dropdown.tsx
components/dropdown/props.ts
components/dropdown/style/index.less
docs/.vitepress/components/dropdown/check.vue
docs/.vitepress/components/dropdown/index.md
docs/.vitepress/components/select/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(Dropdown): 下拉选项容器设置最大高度，超出显示滚动条，及增加 popperClass 配置项，可自定义弹出框容器样式

---

components/virtual-list/virtual.ts
components/virtual-list/virtualList.tsx
docs/.vitepress/components/virtualList/vertical.vue
docs/.vitepress/configs/sidebar/index.ts
package.json

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 修复虚拟滚动组件动态添加子项无法滚动问题

---

components/popper/popper.tsx
docs/.vitepress/components/popper/visible.vue

-   [x] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

fix(Popper): 修复 popperStyle 配置项比默认设置优先级低的问题

---

components/input-file/props.ts
components/input-file/useInputFile.ts
docs/.vitepress/components/inputFile/custom.vue
docs/.vitepress/components/inputFile/index.md

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

feat(InputFile): 增加 FileItem 类型 uid 属性 及完善 自定义 slot 文档示例

---

docs/.vitepress/components/dropdown/check.vue
docs/.vitepress/components/inputFile/custom.vue
docs/.vitepress/components/select/selectGroupOption.vue
docs/.vitepress/components/timeline/customIcon.vue

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

docs: 去掉 lang 为 less 的写法，会导致组件 play 异常

---

components/dropdown/dropdown.tsx
components/dropdown/props.ts
components/dropdown/style/index.less
docs/.vitepress/components/dropdown/check.vue

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No
#910 

feat(Dropdown): 增加 v-model 配置项

---

components/_util/use/useInput.ts
components/select-trigger/selectTrigger.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 修复输入框在中文输入过程中如果被重渲染打断可能无法输入

---

components/tree/style/index.less
docs/.vitepress/components/tree/fix.vue

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No
#917 

feat(Tree): 节点选择箭头图标样式优化，增加点击区域

---

components/table/useTableStyle.ts
docs/.vitepress/components/table/bordered.vue

-   [x] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

fix(Table): 修复左侧列固定的时候，没有滚动条的时候，右侧也会出现阴影的问题

---

components/drawer/drawer.tsx
components/drawer/props.ts
components/locales/lang/enUS.ts
components/locales/lang/zhCN.ts
components/locales/lang/zr.ts
components/tooltip/tooltip.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 修复 Drawer、Tooltip 组件默认按钮的国际化问题

---

components/_style.ts
components/back-top/backTop.tsx
components/back-top/index.ts
components/back-top/props.ts
components/back-top/style/index.less
components/back-top/style/index.ts
components/back-top/useBackTop.ts
components/components.ts
docs/.vitepress/components/backTop/base.vue
docs/.vitepress/components/backTop/container.vue
docs/.vitepress/components/backTop/custom.vue
docs/.vitepress/components/backTop/index.md
docs/.vitepress/configs/sidebar/index.ts

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

feat(BackTop): 增加回到顶部组件

---

components/back-top/props.ts
docs/.vitepress/pwa.ts
package.json
pnpm-lock.yaml

-   [ ] Bugfix
-   [x] Docs
-   [x] Build-related changes
-   [ ] Yes
-   [x] No
```
✓ building client + server bundles...
build error:
HTMLElement is not defined
ReferenceError: HTMLElement is not defined
```

build: 修复 docs:build 报错的问题

---

components/modal/modal.tsx
components/modal/modalApi.tsx
components/modal/props.ts
components/modal/style/index.less
docs/.vitepress/components/modal/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(Modal): 增加 useAnimation 是否使用动画的配置项

---

components/steps/step.tsx
docs/.vitepress/components/steps/common.vue
docs/.vitepress/components/steps/index.md

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

feat(Step): 增加 clickStep 事件

---

components/_util/noticeManager.tsx
components/_util/use/useResize.ts
components/_util/utils.ts
components/carousel/useCarouselPlay.ts
components/image/preview.vue
components/modal/modalApi.tsx
components/popper/useScroll.ts
components/scrollbar/bar.vue
components/scrollbar/scrollbar.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 修复pxfy等函数处理null 问题 &  优化代码避免内存泄露

---

components/button/button.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Button): 修复禁用表单状态下按钮无法点击的问题

---

components/input/style/mixin.less

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#926 

feat(Input): 前缀后缀样式优化

---

components/table/components/bodyTable.tsx
components/table/useTableLayout.ts
components/table/useTableStyle.ts
docs/.vitepress/components/table/sort.vue
package.json
pnpm-lock.yaml

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(FTable): 修复layout:auto时水平滚动计算问题

---

components/draggable/directive.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 清除拖拽事件

---

components/badge/badge.tsx
components/breadcrumb/breadcrumb-item.tsx
components/breadcrumb/breadcrumb.tsx
components/drawer/drawer.tsx
components/float-pane/float-pane.tsx
components/input/input.vue
components/modal/modal.tsx
components/time-picker/time-picker.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 部分组件computed中判断slot存在无响应问题

---

components/popper/popper.tsx
components/popper/props.ts
docs/.vitepress/components/popper/index.md

feat: popper style 支持字符串和数组

---

components/space/props.ts
components/space/space.tsx
docs/.vitepress/components/space/horizontal.vue
docs/.vitepress/components/space/index.md
docs/.vitepress/components/space/vertical.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(Space): 元素间隔方案由 margin 改为 gap

---

components/float-pane/useDrag.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(FloatPane): 拖拽边界检测，判断异常修复

---

components/_style.ts
components/components.ts
components/table/components/virtualTable.tsx
components/table/table.tsx
components/virtual-list/virtual.ts
components/virtual-list/virtualList.tsx
components/virtual-scroller/index.ts
components/virtual-scroller/style/index.ts
components/virtual-scroller/virtual-scroller.tsx
docs/.vitepress/components/table/virtual.vue
docs/.vitepress/components/virtualList/common.vue
docs/.vitepress/components/virtualList/index.md
package.json
pnpm-lock.yaml
tsconfig.base.json

-   [] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [ ] No

feat: fVirtualScroller 性能更好

---

components/modal/modalApi.tsx
docs/.vitepress/components/modal/confirm.vue
docs/.vitepress/components/modal/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(Modal): 全局方法配置项支持 maskClosable，默认为 false

---

pnpm-lock.yaml

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

refactor: 解决 pnpm-lock 不一致导致 docs:build 失败问题

---

components/table/components/virtualTable.tsx
docs/.vitepress/components/table/virtual.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [ ] No

feat: table改为使用virtualList

---

components/tree/useExpand.ts

fix: tree 默认展开全部，支持响应式

---

components/space/props.ts
components/space/space.tsx
docs/.vitepress/components/space/index.md
docs/.vitepress/components/space/vertical.vue
pnpm-lock.yaml

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(Space): 增加 wrapItem 选项，支持配置是否存在包裹子元素的容器

---

components/button/button.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(button): 修复图标显示条件判断逻辑

---

components/table/components/cell.tsx

fix: table null 渲染异常
