WeBankFinTech/fes-design

components/select-tree/selectTree.vue
components/select/optionList.tsx
components/select/props.ts
components/select/select.vue
components/tree/interface.ts
docs/.vitepress/components/select/customOption.vue
docs/.vitepress/components/select/index.md
docs/.vitepress/components/select/labelField.vue
docs/.vitepress/components/selectTree/index.md
docs/.vitepress/components/selectTree/labelField.vue

feat: select提供选项定制和回显内容定制

---

components/modal/modalApi.tsx
docs/.vitepress/components/modal/index.md

Modal confirm closable 属性开放配置

---

components/pagination/jumper.tsx
components/pagination/pagination.tsx
components/pagination/style/index.less
components/pagination/useSpecialModel.ts
docs/.vitepress/components/pagination/index.md

If yes, please describe the impact and migration path for existing applications: 更新以后用户主动改变 currentPage, pageSize 将不会触发相应的事件。之前仅仅依赖监听 change / pageSizeChange 变化然后去请求接口的行为将需要在改变之后主动请求接口。

Pagination 手动设置 currentPage, pageSize 不触发相应事件

---

components/cascader/cascader.tsx
components/cascader/cascaderMenu.tsx
components/cascader/cascaderNode.tsx
components/cascader/const.ts
components/cascader/props.ts
components/cascader/style/index.less
components/cascader/useCascaderMenu.ts
components/cascader/useCascaderNode.ts
components/cascader/useData.ts
components/select-cascader/helper.ts
components/select-cascader/selectCascader.vue
docs/.vitepress/components/selectCascader/async.vue
docs/.vitepress/components/selectCascader/index.md

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
showPath时，若未匹配到值，增加初始化展示的处理

fix: FSelectCascader 兼容 showPath 时未匹配到值的初始化展示

---

components/select-tree/selectTree.vue
components/tree/helper.ts
components/tree/interface.ts
components/tree/tree.tsx
components/tree/useCheck.ts
components/tree/useCurrentData.ts
components/tree/useData.ts
components/tree/useExpand.ts
components/tree/useFilter.ts
components/tree/useSelect.ts
components/tree/useState.ts
docs/.vitepress/components/tree/index.md
docs/.vitepress/components/tree/virtualList.vue

-   [x] Bugfix
-   [ ] Docs
-   [x] Yes
-   [ ] No
`checkStrictly` 不仅影响 check 事件中的 checkedKeys 而且影响属性`checkedKeys`的逻辑，传入的 checkedKeys 需适配 `checkStrictly`。所以当组件配置了`checkStrictly`，且`checkStrictly`不为 `all`时，需要注意：
1. `checkedKeys`默认值需做响应适配
2. 勾选节点后`checkedKeys`的值也会跟上个版本不一样。

break:  Tree 组件 checkStrictly 影响  checkedKeys 逻辑 

---

components/drawer/drawer.tsx
components/drawer/style/index.less
components/virtual-list/listItem.ts
components/virtual-list/props.ts
docs/.vitepress/components/drawer/common.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

refactor: 优化Drawer滚动 & 优化VirtualList参数配置

---

components/tree/interface.ts
components/tree/props.ts
components/tree/useData.ts
components/tree/useDrag.ts
components/tree/useFilter.ts
components/tree/useSelect.ts
docs/.vitepress/components/tree/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: Tree组件选项支持配置是否可拖拽

---

components/tree/style/index.less
components/tree/style/index.ts
components/tree/tree.tsx
components/tree/treeNode.tsx

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: Tree组件节点文本过多省略

---

components/table/column.tsx
components/table/components/bodyTable.tsx
components/table/components/header.tsx
components/table/components/headerTable.tsx
components/table/components/td.tsx
components/table/components/tr.tsx
components/table/helper.ts
components/table/style/index.less
components/table/useTableColumn.ts
components/table/useTableStyle.ts
docs/.vitepress/components/table/fixed.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: Table组件支持配置多个fixed

---

components/upload/upload.tsx
components/upload/useUpload.ts
docs/.vitepress/components/upload/index.md
docs/.vitepress/components/upload/initList.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat: FUpload组件 fileList 支持 v-model 双向绑定

---

components/table/useTableStyle.ts
docs/.vitepress/components/table/fixed.vue
docs/.vitepress/components/table/scroll.vue

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Table): 修复多列Fixed时宽度计算问题

---

components/select/select.vue

fix: select 兼容 options 为 null 的场景

---

components/tabs/helper.ts

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [ ] No

fix: tabs属性displayDirective类型

---

docs/.vitepress/theme/components/exampleRepl.vue
package.json
pnpm-lock.yaml

docs: 优化 repl

---

components/select/interface.ts
components/select/props.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix: 解决option含有其他key的类型异常问题

---

components/calendar/calendar.tsx
components/calendar/calendarNavigator.tsx
components/calendar/props.ts
components/calendar/useCalendarData.ts
components/calendar/useWeekNames.ts
components/calendar/utils.ts
components/collapse/collapse.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#523 

build: 修复构建时类型警告问题

---

components/scrollbar/style/index.less
components/table/components/bodyTable.tsx
components/table/components/virtualTable.tsx
components/table/table.tsx
docs/.vitepress/components/table/index.md
docs/.vitepress/components/table/virtual.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#519 

feat: 滚动条组件宽度修改及 table 组件增加 总是显示滚动条 配置项

---

components/drawer/const.ts
components/drawer/drawer.tsx
components/drawer/index.ts
components/drawer/props.ts
components/drawer/useResizable.ts

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(Drawer): 限制抽屉可拖拽的最大最小尺寸

---

components/date-picker/pickerHandler.ts

-   [x] Bugfix
-   [ ] Yes
-   [x] No
**Related issue (if exists):*https://github.com/WeBankFinTech/fes-design/issues/547*
造成的原因是选择范围的第二个数的天数day会被第一个数覆盖，如果第一个数的day是31，在第二个数是小月的情况下没有31天就会往前进一个月

fix: FDatePicker组件月份范围选择异常

---

docs/postcss.config.mjs
package.json
pnpm-lock.yaml
scripts/genComponentDoc.mjs
tsconfig.eslint.json

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

docs: 防止 vitepress 样式覆盖组件

---

components/upload/upload.tsx
components/upload/useUpload.ts
docs/.vitepress/components/upload/customerUpload.vue
docs/.vitepress/components/upload/index.md

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Upload): 修复有自定义上传逻辑时，action 属性校验必填的报错

---

components/popper/usePopper.ts

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Popper): 修复位置计算逻辑，如 trigger 不可见立即隐藏 Popper

---

components/carousel/arrow.tsx
components/carousel/carousel-item.tsx
components/carousel/carousel.tsx
components/carousel/indicator.tsx
components/carousel/interface.ts
components/carousel/useCarousel.ts
components/carousel/useCarouselItem.ts
components/carousel/useCarouselPlay.ts
components/carousel/useCarouselStyle.ts
docs/.vitepress/components/carousel/default.vue
docs/.vitepress/components/carousel/index.md
docs/.vitepress/components/carousel/params.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Carousel): 修复部分属性响应性失效问题

---

components/select-cascader/selectCascader.vue
components/select-tree/selectTree.vue
docs/.vitepress/components/selectTree/common.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(SelectTree, SelectCascader): expandedKeys 支持 v-model

---

components/_util/utils.ts
components/table/components/cell.tsx

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

fix(Table): 处理 Column.formatter 返回循环依赖对象的情况

---

components/input/style/index.less
components/input/style/mixin.less
docs/.vitepress/components/input/append.vue
docs/.vitepress/components/input/index.md

-   [x] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No

fix(FInput): 修复复合型输入框样式问题

---

components/menu/interface.ts
components/menu/menu.tsx
components/menu/menuItem.tsx
components/menu/style/index.less
docs/.vitepress/components/menu/common.vue
docs/.vitepress/components/menu/index.md
docs/.vitepress/components/menu/options.vue
docs/.vitepress/components/menu/vertical.vue

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(FMenu): 增加 disabled 配置项

---

components/select/optionList.tsx
components/select/props.ts
components/select/select.vue
docs/.vitepress/components/select/filterable.vue
docs/.vitepress/components/select/index.md

-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No
#875 

feat(Select): 增加 filterTextHighlight 过滤文本是否高亮显示的配置项

---

components/descriptions/descriptions.tsx
components/descriptions/interface.ts
components/descriptions/props.ts
components/descriptions/style/index.less
docs/.vitepress/components/descriptions/common.vue
docs/.vitepress/components/descriptions/index.md

-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No

feat(Descriptions): 增加尺寸 size 配置项

---

components/tree/props.ts
components/tree/tree.tsx
components/tree/treeNode.tsx
docs/.vitepress/components/tree/index.md

feat: tree 支持根节点 label slot

---

components/table/components/header.tsx
components/table/table.tsx
components/table/useResize.ts
components/table/useTableLayout.ts
components/table/useTableStyle.ts
package.json

-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [ ] No

fix: 重构表格宽度计算方式

---

components/button/button.tsx
components/button/style/index.less
docs/.vitepress/components/button/icon.vue
docs/.vitepress/components/button/index.md

feat: button icon placement
